# Basic settings
seed_everything: 0
trainer:
  logger: True
  accelerator: gpu
  accumulate_grad_batches: 1
  fast_dev_run: False #False #2 #50
  max_epochs: 15 #30 #2
  check_val_every_n_epoch: 1000 # for blocking validation
  # limit_val_batches: 0
  # limit_train_batches: 5
  num_sanity_val_steps: 0
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: -1
        every_n_epochs: 1
        save_on_train_epoch_end: True


# model config
model:
  dataset_name: BioRED
  lm_checkpoint: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
  task: 'rc' # 'ner', 'cluster', 'rc', 'e2e'
  ner_config:
    class: NER
    config:
      length_embedder:
        class: LengthEmbedding
        config:
          num_embeddings: 100
          embedding_dim: 16
      span_embedder:
        class: SpanEmbedder
        config:
          token_embedder: 
            class: Identity
            config: {}
          token_pooler: 
            function: max_pool
          vector_embedder:
            class: MLP1
            config: 
              output_dim: 128   
      num_entity_classes: {} # to be filled in later    
  clusterer_config:
    class: Coreference
    config: 
      levenshtein_embedder: 
          class: LevenshteinEmbedding
          config:
            num_embeddings: 500
            embedding_dim: 16
      levenshtein_gate:
        class: Gate
        config: {}
      span_embedder:
        class: SpanEmbedder
        config:
          token_embedder: 
            class: Identity
            config: {}
          token_pooler: 
            function: max_pool
          vector_embedder:
            class: Identity
            config: {}
      type_embedder:
        class: TypeEmbedding
        config:
          num_embeddings: 8
          embedding_dim: 16
      length_embedder:
        class: LengthEmbedding
        config:
          num_embeddings: 1000
          embedding_dim: 32
      length_difference_embedder:
        class: LengthDiffEmbedding
        config:
          num_embeddings: 1000
          embedding_dim: 32
      num_coref_classes: 2
      coref_cutoff: 0.5
  rc_config:
    class: RelationClassifier
    config:
      span_embedder: 
        class: SpanEmbedder
        config:
          token_embedder: 
            class: Identity
            config: {}
          token_pooler: 
            function: max_pool
          vector_embedder:
            class: Identity
            config: {}
      intervening_span_embedder: 
        class: SpanEmbedder
        config:
          token_embedder: 
            class: Identity
            config: {}
          token_pooler: 
            function: max_pool
          vector_embedder:
            class: Identity
            config: {}
      span_pooler:
        class: MLP2Pooler
        config:
          intermediate_dim: 128
          output_dim: 64      
      type_embedder: 
        class: TypeEmbedding
        config:
          num_embeddings: 10
          embedding_dim: 16
      local_pooler: 
        class: MLP2Pooler
        config:
          intermediate_dim: 128
          output_dim: 64   
      token_distance_embedder:
        class: TokenDistanceEmbedding
        config:
          num_embeddings: 2048
          embedding_dim: 16
      sentence_distance_embedder:
        class: SentenceDistanceEmbedding
        config:
          num_embeddings: 64
          embedding_dim: 16
      relation_embedder: 
        class: MLP1
        config:
          output_dim: 128
      # prediction_layer:
      #   class: MLP2
      #   config: 
      #     intermediate_dim: 128
      #     output_dim: {} # to be determined in module
      num_relation_classes: {} # to be filled in lightning module
      is_multilabel: False
      rc_cutoff: 0.5
  loss_coefficients: [1,1,1]
  lm_learning_rate: 5e-5
  learning_rate: 1e-3
  ner_scorer_classes:
    - TypedLocationNERScorer
    # - TypedStringNERScorer
    # - UntypedLocationNERScorer
    # - UntypedStringNERScorer
  coref_scorer_classes:
    - TypedLocationCorefScorer
  entity_scorer_classes: 
    - TypedLocationStrictEntityScorer
    # - TypedStringStrictClusterScorer
    # - UntypedLocationStrictClusterScorer
    # - UntypedStringStrictClusterScorer
    - TypedLocationRelaxedEntityScorer
    # - TypedStringRelaxedClusterScorer
    # - UntypedLocationRelaxedClusterScorer
    # - UntypedStringRelaxedClusterScorer
  rc_scorer_classes: 
    - TypedLocationStrictRCScorer
    # - TypedStringStrictRCScorer
    # - UntypedLocationStrictRCScorer
    # - UntypedStringStrictRCScorer
    - TypedLocationRelaxedRCScorer
    # - TypedStringRelaxedRCScorer
    # - UntypedLocationRelaxedRCScorer
    # - UntypedStringRelaxedRCScorer
  calculator_class: Calculator
  neg_to_pos_span_ratio: 14
  neg_to_pos_span_pair_ratio: 7
  span_sampling_probs:
    multi_shift: 0.5
    short: 0.5
  max_span_length: 10

# data config
data:
  dataset_name: BioRED
  lm_checkpoint: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
ckpt_path: null